title: Salaamalykum Open Data Hub
description: The Master Data Catalog and Portal for Islamic Knowledge Bases and RAG Datasets.
collections:
  content:
    output: true
    permalink: /article/:path/

markdown: kramdown
kramdown:
  input: GFM
